language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.0
    - android-29
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

jdk:
  - openjdk8

branches:
  except:
    - gh-pages

licenses:
  - '.+'

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle

script:
  - chmod +x ./gradlew